name: contabilidade_amiga
description: "Um aplicativo para controle de contabilidade de entradas e saídas."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  fl_chart: ^0.68.0
  intl: ^0.19.0

  # ▼▼▼ NOVOS PACOTES ADICIONADOS ▼▼▼
  # Para criar o documento PDF
  pdf: ^3.11.0
  # Para salvar o arquivo no dispositivo e abrir/compartilhar
  path_provider: ^2.1.3
  open_file: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

