// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBno6b6IXh-m0eYCPNPVQm8B5f-wC07Mmc',
    appId: '1:1013473342082:web:2875d05f5393a69774ba9b',
    messagingSenderId: '1013473342082',
    projectId: 'contabilidade-amiga-25e7e',
    authDomain: 'contabilidade-amiga-25e7e.firebaseapp.com',
    storageBucket: 'contabilidade-amiga-25e7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvtrQnNr7vncoFl903IjxZ7T6X0prP9g',
    appId: '1:1013473342082:android:57ab0ce1d2ac296374ba9b',
    messagingSenderId: '1013473342082',
    projectId: 'contabilidade-amiga-25e7e',
    storageBucket: 'contabilidade-amiga-25e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB62LfNYy7j319mKR3ORAlGGezIYsvGsjg',
    appId: '1:1013473342082:ios:564520f4618033ca74ba9b',
    messagingSenderId: '1013473342082',
    projectId: 'contabilidade-amiga-25e7e',
    storageBucket: 'contabilidade-amiga-25e7e.firebasestorage.app',
    iosBundleId: 'com.example.contabilidadeAmiga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB62LfNYy7j319mKR3ORAlGGezIYsvGsjg',
    appId: '1:1013473342082:ios:564520f4618033ca74ba9b',
    messagingSenderId: '1013473342082',
    projectId: 'contabilidade-amiga-25e7e',
    storageBucket: 'contabilidade-amiga-25e7e.firebasestorage.app',
    iosBundleId: 'com.example.contabilidadeAmiga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBno6b6IXh-m0eYCPNPVQm8B5f-wC07Mmc',
    appId: '1:1013473342082:web:83a2cb02695a6e5174ba9b',
    messagingSenderId: '1013473342082',
    projectId: 'contabilidade-amiga-25e7e',
    authDomain: 'contabilidade-amiga-25e7e.firebaseapp.com',
    storageBucket: 'contabilidade-amiga-25e7e.firebasestorage.app',
  );

}